/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testevulnerabilidadeclient;

import static java.sql.Types.INTEGER;

/**
 *
 * @author patri
 */
public class PortScanDos_Client extends javax.swing.JFrame {

    private TesteVulnerabilidadeClient client = null;
    public PortScanDos_Client() {
        initComponents();
        client = new TesteVulnerabilidadeClient(this);
    }
    
    public void recebeMensagemServidor(String receivedServer){
    
        reportList.add(receivedServer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTargetIp = new java.awt.Label();
        txtIpTarget = new java.awt.TextField();
        btStart = new java.awt.Button();
        label2 = new java.awt.Label();
        reportList = new java.awt.List();
        btDos = new java.awt.Button();
        labelPortTarget = new java.awt.Label();
        txtPortTarget = new java.awt.TextField();
        btPortScan = new java.awt.Button();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTargetIp.setBackground(new java.awt.Color(255, 255, 255));
        labelTargetIp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelTargetIp.setText("IP ALVO:");

        txtIpTarget.setName("txtIpTarget"); // NOI18N
        txtIpTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIpTargetActionPerformed(evt);
            }
        });

        btStart.setBackground(new java.awt.Color(153, 255, 204));
        btStart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btStart.setLabel("START TEST");
        btStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btStartMouseReleased(evt);
            }
        });
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(0, 0, 153));
        label2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("VULNERABILITY TESTER");

        reportList.setBackground(new java.awt.Color(0, 0, 0));
        reportList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        reportList.setForeground(new java.awt.Color(0, 153, 0));

        btDos.setBackground(new java.awt.Color(0, 153, 0));
        btDos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btDos.setForeground(new java.awt.Color(255, 255, 255));
        btDos.setLabel("ATTACK DOS");
        btDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDosMouseReleased(evt);
            }
        });

        labelPortTarget.setBackground(new java.awt.Color(255, 255, 255));
        labelPortTarget.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelPortTarget.setText("PORTA ALVO:");

        txtPortTarget.setName("ipTarget"); // NOI18N
        txtPortTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortTargetActionPerformed(evt);
            }
        });

        btPortScan.setBackground(new java.awt.Color(153, 0, 0));
        btPortScan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btPortScan.setForeground(new java.awt.Color(255, 255, 255));
        btPortScan.setLabel("PORTSCAN");
        btPortScan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btPortScanMouseReleased(evt);
            }
        });

        label1.setBackground(new java.awt.Color(255, 255, 153));
        label1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        label1.setText("QUAL TESTE DE VULNERABILIDADE VOCÊ DESEJA REALIZAR?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPortScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(412, 412, 412))
            .addGroup(layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPortTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(reportList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTargetIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIpTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(btStart, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPortScan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTargetIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIpTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPortTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPortTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(reportList, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        btStart.getAccessibleContext().setAccessibleName("START TEST");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIpTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIpTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIpTargetActionPerformed

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btStartActionPerformed

    private void btStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btStartMouseReleased
        
            client.ConexaoServidor();
            
            if(btPortScan.isEnabled()==false){
                if(txtIpTarget.getText().length()!=0)
                    client.enviarDadosPortScan(txtIpTarget.getText());
            }
            else if(btDos.isEnabled()==false){
                if(txtIpTarget.getText().length()!=0 && txtPortTarget.getText().length()!=0)
                    client.enviarDadosDos(txtIpTarget.getText(),txtPortTarget.getText());
            }
            btStart.setEnabled(false);
            
        
    }//GEN-LAST:event_btStartMouseReleased

    private void txtPortTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortTargetActionPerformed

    private void btPortScanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPortScanMouseReleased
        btPortScan.setEnabled(false);
        txtPortTarget.setEnabled(false);
    }//GEN-LAST:event_btPortScanMouseReleased

    private void btDosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDosMouseReleased
        btDos.setEnabled(false);
    }//GEN-LAST:event_btDosMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortScanDos_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortScanDos_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortScanDos_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortScanDos_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortScanDos_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btDos;
    private java.awt.Button btPortScan;
    private java.awt.Button btStart;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label labelPortTarget;
    private java.awt.Label labelTargetIp;
    private java.awt.List reportList;
    private java.awt.TextField txtIpTarget;
    private java.awt.TextField txtPortTarget;
    // End of variables declaration//GEN-END:variables
}
